<?php
//VAMOS DEFINIR O DIRETORIO PRINCIPAL DO NOSSO SITE, PQ SE ALGUEM COLOCAR UM CAMINHO DIFERENTE NA URL NOSSA PAGINA PODE PERDER O ESTILO.CSS, FORA Q FICA MAIS AMIGAVEL 

//AQUI NOS DEFINIMOS QUE O INCLUDE_PATH E UMA VARIALVEL QUE RECEBE O CAMINHO DA NOSSA INDEX.PHP
    define('INCLUDE_PATH','http://localhost/Projeto-01/');

?>